In [5]:
%matplotlib inline
from IPython import display
from matplotlib import pyplot as plt
from mxnet import autograd, nd
import random
import d2l

In [2]:
num_inputs = 2
num_examples = 1000
true_w = nd.array([2, -3.4])
true_b = 4.2
features = nd.random.normal(scale=1, shape=(num_examples, num_inputs))
labels = nd.dot(features, true_w) + true_b
labels += nd.random.normal(scale=0.01, shape=labels.shape)

In [3]:
features


[[ 1.1630787   0.4838046 ]
 [ 0.29956347  0.15302546]
 [-1.1688148   1.5580711 ]
 ...
 [-1.348146    1.541968  ]
 [-2.2382517  -0.34891927]
 [ 0.02030805  1.09498   ]]
<NDArray 1000x2 @cpu(0)>

In [6]:
batch_size = 10

for X, y in d2l.data_iter(batch_size, features, labels):
    print(X, y)
    break


[[ 5.0976288e-01 -3.9156649e-01]
 [ 2.2389311e-01 -2.2365536e-01]
 [ 6.7431526e-04 -7.7242523e-01]
 [ 1.6229826e-01  7.0660716e-01]
 [-1.2246110e+00  2.2329402e+00]
 [ 5.0767344e-01  7.7977628e-02]
 [-7.2658265e-01  1.1108662e+00]
 [-1.6635174e+00  2.5828013e-01]
 [-5.1157194e-01  3.9294311e-01]
 [-4.6581212e-01 -2.8205374e-01]]
<NDArray 10x2 @cpu(0)> 
[ 6.56068    5.4141636  6.8383746  2.1272335 -5.851059   4.9430213
 -1.0402609 -0.0241412  1.8385594  4.217416 ]
<NDArray 10 @cpu(0)>


In [15]:
w = nd.random.normal(scale=0.01, shape=(num_inputs, 1))
b = nd.zeros(shape=(1,))

In [16]:
w.attach_grad()
b.attach_grad()

In [17]:
# This function has been saved in the d2l package for future use
def linreg(X, w, b):
    return nd.dot(X, w) + b

In [18]:
# This function has been saved in the d2l package for future use
def squared_loss(y_hat, y):
    return (y_hat - y.reshape(y_hat.shape)) ** 2 / 2

In [19]:
# This function has been saved in the d2l package for future use
def sgd(params, lr, batch_size):
    for param in params:
        param[:] = param - lr * param.grad / batch_size

In [23]:
lr = 0.03  # Learning rate
num_epochs = 3  # Number of iterations
net = linreg  # Our fancy linear model
loss = squared_loss  # 0.5 (y-y')^2

for epoch in range(num_epochs):
    # Assuming the number of examples can be divided by the batch size, all
    # the examples in the training data set are used once in one epoch
    # iteration. The features and tags of mini-batch examples are given by X
    # and y respectively
    for X, y in d2l.data_iter(batch_size, features, labels):
        with autograd.record():
            l = loss(net(X, w, b), y)  # Minibatch loss in X and y
        l.backward()  # Compute gradient on l with respect to [w,b]
#         print(w.grad)
#         print(b.grad)
        print(w)
        print(b)
        sgd([w, b], lr, batch_size)  # Update parameters using their gradient
    train_l = loss(net(features, w, b), labels)
    print('epoch %d, loss %f' % (epoch + 1, train_l.mean().asnumpy()))


[[ 1.9993137]
 [-3.3998048]]
<NDArray 2x1 @cpu(0)>

[4.1997676]
<NDArray 1 @cpu(0)>

[[ 1.99927  ]
 [-3.3998022]]
<NDArray 2x1 @cpu(0)>

[4.1997304]
<NDArray 1 @cpu(0)>

[[ 1.9994401]
 [-3.3997436]]
<NDArray 2x1 @cpu(0)>

[4.1997075]
<NDArray 1 @cpu(0)>

[[ 1.9993188]
 [-3.3997674]]
<NDArray 2x1 @cpu(0)>

[4.1998587]
<NDArray 1 @cpu(0)>

[[ 1.9991775]
 [-3.3997235]]
<NDArray 2x1 @cpu(0)>

[4.199834]
<NDArray 1 @cpu(0)>

[[ 1.9991416]
 [-3.399685 ]]
<NDArray 2x1 @cpu(0)>

[4.1998205]
<NDArray 1 @cpu(0)>

[[ 1.9990863]
 [-3.3996418]]
<NDArray 2x1 @cpu(0)>

[4.199926]
<NDArray 1 @cpu(0)>

[[ 1.9991103]
 [-3.399677 ]]
<NDArray 2x1 @cpu(0)>

[4.1998863]
<NDArray 1 @cpu(0)>

[[ 1.9990804]
 [-3.399602 ]]
<NDArray 2x1 @cpu(0)>

[4.1999106]
<NDArray 1 @cpu(0)>

[[ 1.9990597]
 [-3.399537 ]]
<NDArray 2x1 @cpu(0)>

[4.19998]
<NDArray 1 @cpu(0)>

[[ 1.9991479]
 [-3.3997962]]
<NDArray 2x1 @cpu(0)>

[4.19999]
<NDArray 1 @cpu(0)>

[[ 1.9991455]
 [-3.3998334]]
<NDArray 2x1 @cpu(0)>

[4.199964]
<NDArra


[[ 1.9989668]
 [-3.399674 ]]
<NDArray 2x1 @cpu(0)>

[4.2008905]
<NDArray 1 @cpu(0)>

[[ 1.9990648]
 [-3.3996708]]
<NDArray 2x1 @cpu(0)>

[4.2008195]
<NDArray 1 @cpu(0)>

[[ 1.9989434]
 [-3.3996897]]
<NDArray 2x1 @cpu(0)>

[4.200832]
<NDArray 1 @cpu(0)>

[[ 1.9989852]
 [-3.3997717]]
<NDArray 2x1 @cpu(0)>

[4.2007184]
<NDArray 1 @cpu(0)>

[[ 1.9989794]
 [-3.3998742]]
<NDArray 2x1 @cpu(0)>

[4.2005577]
<NDArray 1 @cpu(0)>

[[ 1.9989631]
 [-3.399878 ]]
<NDArray 2x1 @cpu(0)>

[4.200637]
<NDArray 1 @cpu(0)>

[[ 1.9990495]
 [-3.3998797]]
<NDArray 2x1 @cpu(0)>

[4.2005734]
<NDArray 1 @cpu(0)>

[[ 1.9988781]
 [-3.3999615]]
<NDArray 2x1 @cpu(0)>

[4.2005286]
<NDArray 1 @cpu(0)>

[[ 1.9989524]
 [-3.3999069]]
<NDArray 2x1 @cpu(0)>

[4.200608]
<NDArray 1 @cpu(0)>

[[ 1.9989681]
 [-3.3997247]]
<NDArray 2x1 @cpu(0)>

[4.200624]
<NDArray 1 @cpu(0)>

[[ 1.9989334]
 [-3.3996685]]
<NDArray 2x1 @cpu(0)>

[4.200604]
<NDArray 1 @cpu(0)>

[[ 1.9989698]
 [-3.3996356]]
<NDArray 2x1 @cpu(0)>

[4.2005906]
<NDAr


[[ 1.9994808]
 [-3.4004579]]
<NDArray 2x1 @cpu(0)>

[4.200556]
<NDArray 1 @cpu(0)>

[[ 1.9993699]
 [-3.4004114]]
<NDArray 2x1 @cpu(0)>

[4.200719]
<NDArray 1 @cpu(0)>

[[ 1.9993664]
 [-3.4004292]]
<NDArray 2x1 @cpu(0)>

[4.200646]
<NDArray 1 @cpu(0)>

[[ 1.9994023]
 [-3.4004114]]
<NDArray 2x1 @cpu(0)>

[4.2006135]
<NDArray 1 @cpu(0)>

[[ 1.9994346]
 [-3.4003851]]
<NDArray 2x1 @cpu(0)>

[4.2005877]
<NDArray 1 @cpu(0)>

[[ 1.9994649]
 [-3.4003134]]
<NDArray 2x1 @cpu(0)>

[4.2005835]
<NDArray 1 @cpu(0)>

[[ 1.9993913]
 [-3.4003305]]
<NDArray 2x1 @cpu(0)>

[4.200487]
<NDArray 1 @cpu(0)>

[[ 1.9993907]
 [-3.4003103]]
<NDArray 2x1 @cpu(0)>

[4.200419]
<NDArray 1 @cpu(0)>

[[ 1.9994769]
 [-3.4003086]]
<NDArray 2x1 @cpu(0)>

[4.200528]
<NDArray 1 @cpu(0)>

[[ 1.9994267]
 [-3.4001994]]
<NDArray 2x1 @cpu(0)>

[4.2005916]
<NDArray 1 @cpu(0)>

[[ 1.9994901]
 [-3.4001496]]
<NDArray 2x1 @cpu(0)>

[4.200619]
<NDArray 1 @cpu(0)>

[[ 1.9994607]
 [-3.3999782]]
<NDArray 2x1 @cpu(0)>

[4.200424]
<NDArray

In [14]:
print('Error in estimating w', true_w - w.reshape(true_w.shape))
print('Error in estimating b', true_b - b)

Error in estimating w 
[-8.8214874e-05 -8.9883804e-05]
<NDArray 2 @cpu(0)>
Error in estimating b 
[0.00038671]
<NDArray 1 @cpu(0)>


In [22]:
true_b

4.2

In [25]:
true_w


[ 2.  -3.4]
<NDArray 2 @cpu(0)>